# Generated by Django 4.0.4 on 2022-05-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='qualification',
            field=models.CharField(choices=[('NA', 'NA'), ('SPM', 'Sijil Pelajaran Malaysia'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor Degree'), ('Master', 'Master Degree'), ('PhD', 'Doctor Degree')], default='NA', max_length=20),
        ),
    ]
