# Generated by Django 4.0.4 on 2022-05-25 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_jobapplication_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
