# Generated by Django 4.0.4 on 2022-05-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_jobapplication_application date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application date',
            new_name='application_date',
        ),
    ]
