# Generated by Django 4.0.4 on 2022-05-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_rename_application date_jobapplication_application_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='working experience',
            new_name='working_experience',
        ),
    ]
